/**
 * Parity tests — the browser Merkle implementation must match the Python prover
 * (`python/merkle.py`) byte-for-byte, because the on-chain
 * `MerkleAnchorRegistry.verifyInclusion` mirrors that same algorithm. A root
 * computed in the browser has to verify on-chain unchanged, so any drift here
 * is a correctness bug, not a style one.
 *
 * The FIXTURE below was generated by running the Python self-test over the
 * 7-part tree `["sub-part-0" … "sub-part-6"]`. Regenerate with:
 *
 *     python -c "import sys; sys.path.insert(0,'python'); import merkle, json; \
 *       parts=[f'sub-part-{i}'.encode() for i in range(7)]; \
 *       leaves=[merkle.sha256_leaf(p) for p in parts]; \
 *       print(json.dumps({'root': merkle.merkle_root(leaves).hex(), \
 *         'proofs':[[s.hex() for s in merkle.merkle_proof(leaves,i)] for i in range(7)]}))"
 */

import { describe, expect, it } from "vitest";

import {
  bytesToHex,
  hexToBytes,
  merkleProof,
  merkleRoot,
  sha256Leaf,
  verifyProof,
} from "./merkle-client";

// Golden vectors from python/merkle.py over ["sub-part-0" … "sub-part-6"].
const FIXTURE = {
  parts: [
    "sub-part-0",
    "sub-part-1",
    "sub-part-2",
    "sub-part-3",
    "sub-part-4",
    "sub-part-5",
    "sub-part-6",
  ],
  leaves: [
    "1338bfcfdb9c1c3edcefb53a654db282ec5ac8d2ebdab317fa8817db8d4302ec",
    "b86abd898cee8be662e446b4dfe03f43bbcbfe95a04ee56f70e7cc15fea9ded8",
    "e96ba43fff5a9b9a4457a317f5c605d9f238628333d24ea82e4898b7f958a053",
    "357fe87c4e71983d940e8aa6ee3caa4f493a9fd66f3d27238f498d1091b56bf5",
    "c70094267dc9752561dd1a0803bebe42426ef16f74127befdb70a5d48d5e8781",
    "8570ec6818543ee20ce9f0556224f87eda915f9f56e76ed580027facb3c020ae",
    "51f85505872b4489126e4618d7e5dda86ffb753b9be6dfc18adbc88ca270c57a",
  ],
  root: "96640394a26a8ac075034ba0317bb5ef9c92e6cd48c1254fc7ac0378c8e085d9",
  proofs: [
    [
      "b86abd898cee8be662e446b4dfe03f43bbcbfe95a04ee56f70e7cc15fea9ded8",
      "e3b7ea4bda177171383cd2015664f7f754b8cc52e7eb1baf38719f4d5668c360",
      "6dd9cfe830bedc1a81d6fe99b3d1f8d1f4b939375d7041e263f112da04e8c8ae",
    ],
    [
      "1338bfcfdb9c1c3edcefb53a654db282ec5ac8d2ebdab317fa8817db8d4302ec",
      "e3b7ea4bda177171383cd2015664f7f754b8cc52e7eb1baf38719f4d5668c360",
      "6dd9cfe830bedc1a81d6fe99b3d1f8d1f4b939375d7041e263f112da04e8c8ae",
    ],
    [
      "357fe87c4e71983d940e8aa6ee3caa4f493a9fd66f3d27238f498d1091b56bf5",
      "db88f036dd5c56bed17ddccd56ff346610a252b7c17e6771d9acc009d2774f1a",
      "6dd9cfe830bedc1a81d6fe99b3d1f8d1f4b939375d7041e263f112da04e8c8ae",
    ],
    [
      "e96ba43fff5a9b9a4457a317f5c605d9f238628333d24ea82e4898b7f958a053",
      "db88f036dd5c56bed17ddccd56ff346610a252b7c17e6771d9acc009d2774f1a",
      "6dd9cfe830bedc1a81d6fe99b3d1f8d1f4b939375d7041e263f112da04e8c8ae",
    ],
    [
      "8570ec6818543ee20ce9f0556224f87eda915f9f56e76ed580027facb3c020ae",
      "51f85505872b4489126e4618d7e5dda86ffb753b9be6dfc18adbc88ca270c57a",
      "57479d0595dd3f56f36d7c64cb2f874919d8ced79deb36c801344f68c3e78af0",
    ],
    [
      "c70094267dc9752561dd1a0803bebe42426ef16f74127befdb70a5d48d5e8781",
      "51f85505872b4489126e4618d7e5dda86ffb753b9be6dfc18adbc88ca270c57a",
      "57479d0595dd3f56f36d7c64cb2f874919d8ced79deb36c801344f68c3e78af0",
    ],
    [
      "ac934ec5c03300768d035ff883c759604688fa3da0c7d879a366233a75d2d893",
      "57479d0595dd3f56f36d7c64cb2f874919d8ced79deb36c801344f68c3e78af0",
    ],
  ],
  emptyRoot: "0000000000000000000000000000000000000000000000000000000000000000",
  singleRoot: "1338bfcfdb9c1c3edcefb53a654db282ec5ac8d2ebdab317fa8817db8d4302ec",
};

const enc = new TextEncoder();
const leaves = FIXTURE.parts.map((p) => sha256Leaf(enc.encode(p)));

describe("merkle-client parity with python/merkle.py", () => {
  it("hashes each leaf to the same bytes as Python", () => {
    leaves.forEach((leaf, i) => {
      expect(bytesToHex(leaf)).toBe(`0x${FIXTURE.leaves[i]}`);
    });
  });

  it("computes the same root as Python over a 7-leaf tree", () => {
    expect(bytesToHex(merkleRoot(leaves))).toBe(`0x${FIXTURE.root}`);
  });

  it("generates the exact same proof bytes as Python for every leaf", () => {
    FIXTURE.proofs.forEach((expectedProof, i) => {
      const proof = merkleProof(leaves, i);
      expect(proof.map(bytesToHex)).toEqual(expectedProof.map((h) => `0x${h}`));
    });
  });

  it("verifies every fixture proof against the root", () => {
    const root = hexToBytes(FIXTURE.root);
    leaves.forEach((leaf, i) => {
      const proof = FIXTURE.proofs[i].map((h) => hexToBytes(h));
      expect(verifyProof(leaf, proof, root)).toBe(true);
    });
  });

  it("round-trips a self-computed proof through verify", () => {
    const root = merkleRoot(leaves);
    leaves.forEach((leaf, i) => {
      expect(verifyProof(leaf, merkleProof(leaves, i), root)).toBe(true);
    });
  });
});

describe("merkle-client edge cases", () => {
  it("empty tree is the 32-zero-byte sentinel root", () => {
    expect(bytesToHex(merkleRoot([]))).toBe(`0x${FIXTURE.emptyRoot}`);
  });

  it("single-leaf tree is the leaf itself", () => {
    expect(bytesToHex(merkleRoot([leaves[0]]))).toBe(`0x${FIXTURE.singleRoot}`);
  });

  it("single-leaf proof is empty and still verifies", () => {
    const proof = merkleProof([leaves[0]], 0);
    expect(proof).toEqual([]);
    expect(verifyProof(leaves[0], proof, leaves[0])).toBe(true);
  });

  it("rejects a tampered leaf", () => {
    const root = merkleRoot(leaves);
    const wrong = sha256Leaf(enc.encode("not-a-real-part"));
    expect(verifyProof(wrong, merkleProof(leaves, 2), root)).toBe(false);
  });

  it("rejects a proof element of the wrong length", () => {
    const root = merkleRoot(leaves);
    const badProof = [new Uint8Array(31)]; // not 32 bytes
    expect(verifyProof(leaves[0], badProof, root)).toBe(false);
  });

  it("throws when proving an out-of-range index", () => {
    expect(() => merkleProof(leaves, 99)).toThrow();
  });
});
